from langchain_community.llms import Ollama
from langchain_core.prompts import PromptTemplate

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

from nl2sql.validator import validate_sql
from nl2sql.executor import execute_sql

# -------------------------
# Few-shot NL → SQL examples
# -------------------------
FEW_SHOT_EXAMPLES = [
    {
        "question": "Show total sales by category",
        "sql": """
        SELECT
            p.category,
            SUM(oi.quantity * oi.unit_price) AS total_sales
        FROM order_items oi
        JOIN products p ON oi.product_id = p.product_id
        GROUP BY p.category;
        """
    },
    {
        "question": "Top 5 products by revenue",
        "sql": """
        SELECT
            p.product_name,
            SUM(oi.quantity * oi.unit_price) AS revenue
        FROM order_items oi
        JOIN products p ON oi.product_id = p.product_id
        GROUP BY p.product_name
        ORDER BY revenue DESC
        LIMIT 5;
        """
    },
    {
        "question": "Total number of orders per country",
        "sql": """
        SELECT
            c.country,
            COUNT(o.order_id) AS total_orders
        FROM orders o
        JOIN customers c ON o.customer_id = c.customer_id
        GROUP BY c.country;
        """
    },
    {
        "question": "Average product rating by category",
        "sql": """
        SELECT
            p.category,
            AVG(r.rating) AS avg_rating
        FROM reviews r
        JOIN products p ON r.product_id = p.product_id
        GROUP BY p.category;
        """
    },
    {
        "question": "Total revenue generated by each customer",
        "sql": """
        SELECT
            c.customer_id,
            SUM(oi.quantity * oi.unit_price) AS total_revenue
        FROM customers c
        JOIN orders o ON c.customer_id = o.customer_id
        JOIN order_items oi ON o.order_id = oi.order_id
        GROUP BY c.customer_id;
        """
    }
]

# -------------------------
# Build FAISS vector store
# -------------------------
def build_example_vector_store():
    texts = [
        f"Question: {ex['question']}\nSQL: {ex['sql']}"
        for ex in FEW_SHOT_EXAMPLES
    ]

    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

    vector_store = FAISS.from_texts(texts, embedding=embeddings)
    return vector_store

# -------------------------
# Initialize LLM
# -------------------------
llm = Ollama(
    model="mistral",
    temperature=0,
    timeout=120
)


# -------------------------
# Prompt Template
# -------------------------
# prompt_template = """
# You are an expert SQL generator.

# Rules:
# - Generate ONLY valid PostgreSQL SQL
# - Do NOT explain anything
# - Do NOT use tables or columns not listed
# - Use proper JOINs
# - Output ONLY the SQL query

# Schema:
# customers(customer_id, first_name, last_name, gender, age_group, signup_date, country)
# orders(order_id, customer_id, order_date, order_status, payment_method)
# order_items(order_item_id, order_id, product_id, quantity, unit_price)
# products(product_id, product_name, category, unit_price)
# reviews(review_id, customer_id, product_id, rating, review_text, review_date)

# Question:
# {question}
# """
prompt_template = """
You are an expert SQL generator.

Rules:
- Generate ONLY valid PostgreSQL SQL
- Do NOT explain anything
- Do NOT use tables or columns not listed
- Use proper JOINs
- Output ONLY the SQL query

Schema:
customers(customer_id, first_name, last_name, gender, age_group, signup_date, country)
orders(order_id, customer_id, order_date, order_status, payment_method)
order_items(order_item_id, order_id, product_id, quantity, unit_price)
products(product_id, product_name, category, unit_price)
reviews(review_id, customer_id, product_id, rating, review_text, review_date)

Examples:
{examples}

Question:
{question}
"""

prompt = PromptTemplate(
    input_variables=["question"],
    template=prompt_template
)


# -------------------------
# NL → SQL function
# -------------------------
# def generate_sql(question: str) -> str:
#     formatted_prompt = prompt.format(question=question)
#     sql_query = llm.invoke(formatted_prompt)
#     return sql_query.strip()
vector_store = build_example_vector_store()

def generate_sql(question: str) -> str:
    docs = vector_store.similarity_search(question, k=3)
    examples_text = "\n\n".join(doc.page_content for doc in docs)

    formatted_prompt = prompt.format(
        question=question,
        examples=examples_text
    )
    #try 1st
    # sql_query = llm.invoke(formatted_prompt)
    # return sql_query.strip() 
    #try 2nd
    # sql_query = llm.invoke(formatted_prompt)

    # # --- HARDEN OUTPUT ---
    # sql_query = sql_query.strip()

    # # Remove code fences if LLM adds them
    # if sql_query.startswith("```"):
    #     sql_query = sql_query.replace("```sql", "").replace("```", "").strip()

    # # Keep only the first SELECT statement
    # select_index = sql_query.lower().find("select")
    # if select_index != -1:
    #     sql_query = sql_query[select_index:]

    # return sql_query    

    #try 3rd
    sql_query = llm.invoke(formatted_prompt)

    # ---------- HARD CLEANING ----------
    sql_query = sql_query.strip()

    # Remove markdown code fences completely
    sql_query = sql_query.replace("```sql", "")
    sql_query = sql_query.replace("```", "")

    # Remove leading/trailing junk lines
    lines = sql_query.splitlines()
    clean_lines = []

    for line in lines:
        line = line.strip()
        if line:
            clean_lines.append(line)

    sql_query = " ".join(clean_lines)

    # Force SQL to start at SELECT
    select_index = sql_query.lower().find("select")
    if select_index != -1:
        sql_query = sql_query[select_index:]

    return sql_query

# -------------------------
# Manual test
# -------------------------

# if __name__ == "__main__":
#     # q = "Show total sales by category"
#     # q = "Top 3 categories by revenue"
#     # q = "Average rating per product"
#     q = "Total orders by payment method"
#     print(generate_sql(q))

if __name__ == "__main__":
    question = "Show total sales by category"
    # question = "Total orders by payment method"
    # print("User Question:", query.question)

    sql = generate_sql(question)
    print("Generated SQL:\n", sql)

    validate_sql(sql)

    print("\nExecution Result:")
    result = execute_sql(sql)
    print(result)
